
CREATE TABLE Product (
    maker VARCHAR(10) NOT NULL,
    model VARCHAR(50) PRIMARY KEY,
    type VARCHAR(50) NOT NULL CHECK (type IN ('PC', 'Laptop', 'Printer'))
);

CREATE TABLE PC (
    code INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model VARCHAR(50) NOT NULL,
    speed SMALLINT NOT NULL CHECK (speed > 0),
    ram SMALLINT NOT NULL CHECK (ram >= 0),
    hd REAL NOT NULL CHECK (hd >= 0),
    cd VARCHAR(10) NOT NULL,
    price MONEY,
    FOREIGN KEY (model) REFERENCES Product(model)
);

CREATE TABLE Laptop (
    code INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model VARCHAR(50) NOT NULL,
    speed SMALLINT NOT NULL CHECK (speed > 0),
    ram SMALLINT NOT NULL CHECK (ram >= 0),
    hd REAL NOT NULL CHECK (hd >= 0),
    screen SMALLINT NOT NULL CHECK (screen > 0),
    price MONEY,
    FOREIGN KEY (model) REFERENCES Product(model)
);

CREATE TABLE Printer (
    code INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model VARCHAR(50) NOT NULL,
    color CHAR(1) NOT NULL CHECK (color IN ('y', 'n')),
    type VARCHAR(10) NOT NULL CHECK (type IN ('Laser', 'Jet', 'Matrix')),
    price MONEY,
    FOREIGN KEY (model) REFERENCES Product(model)
);